# Input data
input_reads: "/data/groups/wheelenj/sequencing/20250916_M009242/planaria_test_subset.fastq.gz"

# Genome parameters
genome_size: "1g"

filtlong:
  min_length: 1000
  keep_percent: 80
  # target_bases: 120000000000
  min_mean_q: 8

flye:
  iterations: 2

medaka:
  model: "r1041_e82_400bps_sup_g615" 
  batch_size: 100

racon:
  rounds: 3

busco:
  lineage: "metazoa_odb10"

threads:
  flye: 64
  medaka: 64
  racon: 64
  busco: 64
  purge_dups: 32

memory:  # in MB
  flye: 200000
  medaka: 128000
  racon: 128000

